config/routes.rb
Rails.application.routes.draw do

  root "pages#home"

  get '/home' => "pages#home"

  resources :rumors

  resources :classifieds

  resources :users, only: [:get, :show, :new, :create, :edit, :index, :update, :destroy]

  resources :sessions, only: [:new, :create, :destroy, :edit, :patch]
  get '/login', to: 'sessions#new'

end

app/models/classified.rb
class Classified < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image_one_url, styles: { medium: "300x300>",
    thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image_one_url,
    content_type: /\Aimage\/.*\Z/
  has_attached_file :image_two_url, styles: { medium: "300x300>",
    thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image_two_url, content_type: /\Aimage\/.*\Z/

end

app/models/rumor.rb
class Rumor < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :classifieds, dependent: :destroy
  has_many :rumors, dependent: :destroy
  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

    helper_method :current_user, :is_admin

    def current_user
      # reset_session
      @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end

    def authorize
      redirect_to login_path, alert: 'You must be logged in' if current_user.nil?
    end

    def is_admin
      current_user && current_user.admin?
    end
end

app/controllers/classifieds_controller.rb
class ClassifiedsController < ApplicationController
  before_action :authorize, except: [:index, :show]

  def new
    @classified = Classified.new
  end

  def create
    @classified = Classified.new(classified_params)
    @classified.user_id = current_user.id
    @classified.email = current_user.email

    if @classified.save
      flash[:notice] = "New classified created!"
      redirect_to classified_path(@classified)
    else
      render :new
    end
  end

  def index
    @classifieds = Classified.order('created_at DESC').all
  end

  def show
    @classified = Classified.find(params[:id])
  end

  def edit
    @classified = Classified.find(params[:id])
  end

  def update
    @classified = Classified.find(params[:id])
    if @classified.update_attributes(params.require(:classified).permit(:user_id, :post_type, :machine_name, :body_text, :condition, :price, :location, :image_one_url, :image_two_url))
      redirect_to classifieds_path
    else
      render :edit
    end
  end

  def destroy
    @classified = Classified.find(params[:id])
    @classified.destroy
    redirect_to classifieds_path
  end


private

    def classified_params
      params.require(:classified).permit(:user_id, :post_type, :body_text, :machine_name, :condition, :price, :location, :image_one_url, :image_two_url)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @classifieds = Classified.all
    @rumors = Rumor.all
  end

end

app/controllers/rumors_controller.rb
class RumorsController < ApplicationController
  before_action :authorize, except: [:index, :show]

  def new
    @rumor = Rumor.new
  end

  def create
    @rumor = Rumor.new(rumor_params)
    @rumor.user_id = current_user.id

    if @rumor.save
      flash[:notice] = "You started a new rumor!"
      redirect_to rumor_path(@rumor)
    else
      render :new
    end
  end

  def index
    @rumors = Rumor.order('created_at DESC').all
  end

  def show
    @rumor = Rumor.find(params[:id])
  end

  def edit
    @rumor = Rumor.find(params[:id])
  end

  def update
    @rumor = Rumor.find(params[:id])
    if @rumor.update_attributes(params.require(:rumor).permit(:title, :body_text))
      redirect_to rumors_path
    else
      render :edit
    end
  end

  def destroy
    @rumor = Rumor.find(params[:id])
    @rumor.destroy
    redirect_to rumors_path
  end

  private

    def rumor_params
      params.require(:rumor).permit(:user_id, :title, :body_text)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Logged in!'
    else
      flash.now.alert = 'Invalid login, please try again.'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "See you soon"
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authorize, except: [:index, :show, :new, :create]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to PinHeads!"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params.require(:user).permit(:first_name, :last_name, :email, :initials, :born_on, :machines_owned, :password, :password_confirmation))
      redirect_to users_path
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :initials, :born_on, :machines_owned, :admin, :password, :password_confirmation)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classifieds_helper.rb
module ClassifiedsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rumors_helper.rb
module RumorsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/classifieds/create.html.erb
<h1>Classifieds#create</h1>
<p>Find me in app/views/classifieds/create.html.erb</p>

app/views/classifieds/edit.html.erb
<div class="container">
  <div class="edit">
    <%= bootstrap_form_for @classified, html: { multipart: true } do |f| %>
      <% if @classified.errors.any? %>
        <div class="error_messages">
          <h2>Hmmmm, something's wrong with your post</h2>
          <ul>
            <% for message in @classified.errors.full_messages %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= f.text_field :post_type %>
      <%= f.text_field :machine_name %>
      <%= f.text_area :body_text, as: :textarea, class: "form-control",rows: "5" %>
      <%= f.text_field :condition %>
      <%= f.text_field :price %>
      <%= f.text_field :location %>
      <%= f.file_field :image_one_url, as: :file  %>
      <%= f.file_field :image_two_url, as: :file  %>
      <div class="actions"><%= f.submit %></div>
    <% end %>
    <p><%= link_to "Delete post!", classified_path, method: :delete, data: { confirm: "Are you sure you want to delete?"}, :class => "link" %></p>
    <p><%= link_to "back to main user page", classifieds_path, :class => "link" %></p>
  </div>
</div>

app/views/classifieds/index.html.erb
<div class="col-sm-8 col-sm-offset-2" id="classified_index">
  <h1 class="group_title">Classifieds!</h1>
  <h3 class="group_title"><%= link_to "Make a new classified ad!", new_classified_path, :class => "link"  %></h3>
    <% @classifieds.each do |classified| %>
      <div id="c_index_each">
        <p class="lead"><%= classified.post_type %> :&nbsp <%= classified.machine_name %></p>
        <% if classified.image_one_url(:medium) != "/images/medium/missing.png" %>
          <p><a><%= image_tag classified.image_one_url(:medium), :class => "pic"%></a>
        <% end %>
        <% if classified.image_two_url(:medium) != "/images/medium/missing.png" %>
          <a><%= image_tag classified.image_two_url(:medium), :class => "pic"%></a>
        <% end %>
        <p><%= classified.body_text %></p>
        <p><strong>Condition: </strong><%= classified.condition %> | <strong>Location: </strong><%= classified.location %> | <strong>Price: $</strong><%= classified.price %> | Posted on: <%= classified.created_at.strftime("%m-%d-%Y") %></p>
        <p><strong>Contact me at: </strong><a href="mailto:<%= classified.email %>" class="link"><%= classified.email %></a></p>
        <% if current_user == nil %>
          <p></p>
        <% elsif classified.user_id == current_user.id || is_admin %>
          <p><%= link_to "Show ", classified_path(classified), :class => "link" %><%= link_to "Edit", edit_classified_path(classified), :class => "link" %> <%= link_to 'Delete', classified, method: :delete, data: { confirm: 'Are you sure?' }, :class => "link" %></p>
        <% end %>
      </div>
    <% end %>
</div>

app/views/classifieds/new.html.erb
<div class="container">
  <div class="edit">
    <%= bootstrap_form_for @classified, html: { multipart: true } do |f| %>
      <% if @classified.errors.any? %>
        <div class="error_messages">
          <h2>Hmmmm, something's wrong with your post</h2>
          <ul>
            <% for message in @classified.errors.full_messages %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= f.text_field :post_type %>
      <%= f.text_field :machine_name %>
      <%= f.text_area :body_text, as: :textarea, class: "form-control",rows: "5" %>
      <%= f.text_field :condition %>
      <%= f.text_field :price %>
      <%= f.text_field :location %>
      <%= f.file_field :image_one_url, as: :file  %>
      <%= f.file_field :image_two_url, as: :file  %>
      <div class="actions"><%= f.submit %></div>
    <% end %>
  </div>
</div>

app/views/classifieds/show.html.erb
<div class="col-sm-8 col-sm-offset-2" id="classified_index">
  <div id="c_index_each">
    <p><strong><%= @classified.post_type %> :&nbsp <%= @classified.machine_name %></strong></p>
    <% if @classified.image_one_url(:medium) != "/images/medium/missing.png" %>
        <p><a><%= image_tag @classified.image_one_url(:medium), :class => "pic"%></a>
    <% end %>
    <% if @classified.image_two_url(:medium) != "/images/medium/missing.png" %>
      <a><%= image_tag @classified.image_two_url(:medium), :class => "pic"%></a>
    <% end %>
    <p><%= @classified.body_text %></p>
    <p><strong>Condition: </strong><%= @classified.condition %> | <strong>Location: </strong><%= @classified.location %> | <strong>Price: $</strong><%= @classified.price %> </p>
    <p><strong>contact me at: </strong><a href="mailto:<%= @classified.email %>" class="link"><%= @classified.email %></a></p>
  </div>
  <% if current_user == nil %>
    <p></p>
  <% elsif @classified.user_id == current_user.id || is_admin %>
    <div class="links">
      <p><%= link_to "Make a mistake? Edit your post!", edit_classified_path, :class => "link"%></p>
      <p><%= link_to "I'm full of regret!! Delete!", classified_path, method: :delete, data: { confirm: "Are you sure you want to delete?"} , :class => "link" %></p>
      <p><strong><%= link_to "I love it!! Take me to the classifieds!", classifieds_path, :class => "link" %></strong></p>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PinHeads!</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
</head>
<body>
  <header class="navbar navbar-static-top" id="navs">
    <ul class="nav navbar-nav pull-right" id="login">
      <% if current_user %>
        <li roll="presentation"><a class="welcome">Welcome, <%= current_user.first_name %>!</a></li>
        <li roll="presentation"><%= link_to 'Logout', session_path('dummy'), method: :delete, :class => "link"%></li>
      <% else %>
        <li roll="presentation"></li>
        <li roll="presentation"><%= link_to 'Login', login_path, :class => "link" %></li>
        <li roll="presentation"><%= link_to "Sign Up", new_user_path, :class => "link" %></li>
      <% end %>
    </ul>
    <ul class="nav navbar-nav pull-left">
      <li roll="presentation" class="active"><%= link_to "PinHeads", root_path, :class => "home" %></li>
      <li roll="presentation" class="active"><%= link_to "Classifieds", classifieds_path, :class => "link" %></li>
      <li roll="presentation" class="active"><%= link_to "Rumors", rumors_path, :class => "link" %></li>
      <li roll="presentation" class="active">
        <% if current_user == nil %>
          <p></p>
        <% elsif current_user.id == current_user.id || is_admin %>
        <%= link_to "Users", users_path, :class => "link" %>
        <% end %>
      </li>
    </ul>
  </header>
  <%= yield %>
</body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div class="row top-buffer">
    <div class="col-sm-4" id="mini_classifieds">
      <h2>What's new in classifieds</h3>
      <p><%= link_to "See all classifieds", classifieds_path, :class => "link" %></p>
      <p><%= link_to "Post a new classified ad!", new_classified_path, :class => "link" %></p>
      <div id="classified_headlines">
        <% @classifieds.order('created_at DESC').limit(10).each do |classified| %>
          <div class="short_classified">
            <a href="/classifieds/<%=classified.id %>"><%= classified.post_type %> :&nbsp  <%= classified.machine_name %></a>
          </div>
        <% end %>
    </div>
  </div>
  <div class="col-sm-6 col-sm-offset-2" id="news">
    <h2>Rumor Roundup!</h2>
    <p><%= link_to "See all rumors", rumors_path, :class => "link" %></p>
    <p><%= link_to "Start a new rumor!", new_rumor_path, :class => "link" %></p>
    <div id="rumor_headlines">
      <% @rumors.order('created_at DESC').limit(3).each do |rumor| %>
        <div id="article">
          <p class="lead"><%= rumor.title %></p>
          <p><%= rumor.body_text %></p>
          <p><small>Spread by <%= rumor.user.initials %> on <%= rumor.created_at.strftime("%m-%d-%Y") %></small></p>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/rumors/create.html.erb
<h1>Rumors#create</h1>
<p>Find me in app/views/rumors/create.html.erb</p>

app/views/rumors/edit.html.erb
<div class="container">
  <div class="edit">
    <h1>Edit this rumor!</h1>
    <%= bootstrap_form_for @rumor do |f| %>
      <% if @rumor.errors.any? %>
        <div class="error_messages">
          <h2>Hmmmm, something's wrong with your post</h2>
          <ul>
            <% for message in @classified.errors.full_messages %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= f.text_field :title %>
      <%= f.text_area :body_text, as: :textarea, class: "form-control",rows: "5" %>
      <div class="actions"><%= f.submit %></div>
    <% end %>
    <% if current_user == nil %>
      <p></p>
    <% elsif @rumor.user_id == current_user.id || is_admin %>
      <p><%= link_to "Delete post!", rumor_path, method: :delete, data: { confirm: "Are you sure you want to delete?"}, :class => "link" %></p>
    <% end %>
    <p><%= link_to "back to main rumor page", rumor_path, :class => "link" %></p>
  </div>
</div>

app/views/rumors/index.html.erb
<div class="col-sm-8 col-sm-offset-2" id="classified_index">
  <h1 class="group_title">Rumors!</h1>
  <h3 class="group_title"><%= link_to "Start a new rumor!", new_rumor_path, :class => "link" %></h3>
  <% @rumors.each do |rumor| %>
    <div id="c_index_each">
      <p class="lead"><%= rumor.title %></p>
      <p><%= rumor.body_text %></p>
      <p><small>Spread by <%= rumor.user.initials %> on <%= rumor.created_at.strftime("%m-%d-%Y") %></small></p>
      <% if current_user == nil %>
        <p></p>
      <% elsif rumor.user_id == current_user.id || is_admin %>
       <p><%= link_to "Edit", edit_rumor_path(rumor), :class => "link" %> <%= link_to 'Delete', rumor, method: :delete, data: { confirm: 'Are you sure?' }, :class => "link" %></p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/rumors/new.html.erb
<div class="container">
  <div class="edit">
    <h1>Create a new rumor!</h1>
    <%= bootstrap_form_for @rumor do |f| %>
      <% if @rumor.errors.any? %>
        <div class="error_messages">
          <h2>Hmmmm, something's wrong with your post</h2>
          <ul>
            <% for message in @classified.errors.full_messages %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= f.text_field :title %>
      <%= f.text_area :body_text, as: :textarea, class: "form-control",rows: "5" %>
      <div class="actions"><%= f.submit %></div>
    <% end %>
  </div>
</div>

app/views/rumors/show.html.erb
<div class="col-sm-8 col-sm-offset-2" id="classified_index">
  <div class="c_index_each">
    <p><strong><%= @rumor.title %></strong></p>
    <p><%= @rumor.body_text %></p>
    <p><small>Spread by <%= @rumor.user.initials %> on <%= @rumor.created_at.strftime("%m-%d-%Y") %></small></p>
  </div>
  <% if current_user == nil %>
    <p></p>
  <% elsif @rumor.user_id == current_user.id || is_admin %>
    <p class="links"><%= link_to "This rumor is full of lies! Edit!", edit_rumor_path, :class => "link"  %></p>
    <p class="links"><%= link_to "This rumor is just outright wrong! Delete!", rumor_path, method: :delete, data: { confirm: "Are you sure you want to delete?"} %></p>
  <% end %>
  <p class="links"><strong><%= link_to "I love it!! Take me to the rumors", rumors_path, :class => "link" %></strong></p>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<div class="container">
  <div class="edit">
    <h1>Edit user</h1>
    <%= bootstrap_form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Hmmmm, something's wrong with your entry</h2>
          <ul>
            <% for message in @user.errors.full_messages %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= f.text_field :first_name %>
      <%= f.text_field :last_name %>
      <%= f.text_field :initials %>
      <%= f.text_field :email %>
      <%= f.date_select :born_on, order: [:month, :day, :year], start_year: 1910 %>
      <%= f.text_field :machines_owned %>
      <%= f.text_field :password %>
      <%= f.text_field :password_confirmation %>
      <div class="actions"><%= f.submit %></div>
    <% end %>
    <% if current_user == nil %>
      <p></p>
    <% elsif @user == current_user || is_admin %>
      <p><%= link_to "Delete user!", user_path, method: :delete, data: { confirm: "Are you sure you want to delete?"}, :class => "link" %></p>
    <% end %>
    <p><%= link_to "back to main user page", users_path, :class => "link" %></p>
  </div>
</div>

app/views/users/index.html.erb
<div class="col-sm-6 col-sm-offset-3" id="user_index">
  <h1>Index list of all users</h1>
  <% @users.each do |user| %>
    <div id="u_index_each">
      <p><%= user.email %></p>
      <% if current_user == nil %>
        <p></p>
       <% elsif user == current_user || is_admin %>
        <p><%= link_to "Show", user, :class => "link" %> <%= link_to "Edit", edit_user_path(user), :class => "link" %> <%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' }, :class => "link" %></p>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="container">
  <div class="edit">
    <h1>Sign Up</h1>
    <%= bootstrap_form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Hmmmm, something's wrong with your entry</h2>
            <ul>
              <% for message in @user.errors.full_messages %>
                <li><%= message %></li>
              <% end %>
            </ul>
        </div>
      <% end %>
      <%= f.text_field :first_name %>
      <%= f.text_field :last_name %>
      <%= f.text_field :initials %>
      <%= f.text_field :email %>
      <%= f.date_select :born_on, order: [:month, :day, :year], start_year: 1910 %>
      <%= f.text_field :machines_owned %>
      <%= f.password_field :password %>
      <%= f.password_field :password_confirmation %>
      <div class="actions"><%= f.submit %></div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="col-sm-8 col-sm-offset-2" id="classified_index">
  <h1> Up close and personal! </h1>
  <div id="c_index_each">
    <p><strong><%= @user.first_name %><%= @user.last_name %></strong></p>
    <p><%= @user.initials %></p>
    <p><%= @user.born_on %></p>
    <p><%= @user.email %></p>
    <p><%= @user.machines_owned %></p>
  </div>
  <% if current_user == nil %>
    <p></p>
  <% elsif @user.id == current_user.id || is_admin %>
    <p><%= link_to "Make a mistake? Edit user!", edit_user_path, :class => "link" %></p>
    <p><%= link_to "I'm full of regret, I like Galaga, not pinball!! Delete!", user_path, method: :delete, data: { confirm: "Are you sure you want to delete?"}, :class => "link" %></p>
  <% end %>
  <p><%= link_to "Show me the users!!", users_path, :class => "link" %></p>
</div>